### PR TITLE
Renaming content #146

### PR DESCRIPTION
**Pull request by JimTharioAmazon**
**Note: this PR is being merged directly to main. Merge to 1.1.0 branches as needed.**

*Issue #, if available:* #146

*Description of changes:*
Renaming content for the solution name change (no code)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by thyagram-aws** [comment]
- We could change the **About** section in the GitHub main page repository details. 
_AWS Virtual Waiting Room solution..._  => _Virtual Waiting Room on AWS solution..._

- Additionally the file names in the `deployment/ ` folder could be renamed from _aws-virtual-waiting-room-getting-started.json_ to _virtual-waiting-room-on-aws-getting-started.json_ though this would entail other changes like the _File Structure_ section in the landing page.

**Comment by thyagram-aws** [comment]
The deployment template themselves have fields like `"Description": "AWS Virtual Waiting Room ... "` .
We also have miscellaneous titles and comments in some files with the _AWS Virtual Waiting Room_ text. 

Summary of files: 

```
deployment/aws-virtual-waiting-room-api-gateway-cw-logs-role.json:
  2    "AWSTemplateFormatVersion": "2010-09-09",
  3:   "Description": "AWS Virtual Waiting Room API Gateway CW Logs Role %%VERSION%%",
  4    "Resources": {

deployment/aws-virtual-waiting-room-getting-started.json:
  2      "AWSTemplateFormatVersion": "2010-09-09",
  3:     "Description": "AWS Virtual Waiting Room Getting Started %%VERSION%%",
  4      "Resources": {

deployment/aws-virtual-waiting-room-sample-inlet-strategy.json:
  2      "AWSTemplateFormatVersion": "2010-09-09",
  3:     "Description": "AWS Virtual Waiting Room Inlet Strategies %%VERSION%%",
  4      "Mappings": {

deployment/aws-virtual-waiting-room.json:
  2      "AWSTemplateFormatVersion": "2010-09-09",
  3:     "Description": "(SO0166) AWS Virtual Waiting Room %%VERSION%%",
  4      "Mappings": {

source/control-panel/src/App.vue:
  48    created() {
  49:     document.title = "AWS Virtual Waiting Room Control Panel";
  50    },

source/control-panel/src/components/Banner.vue:
   9    <div class="d-flex justify-content-center">
  10:     <p class="h4">AWS Virtual Waiting Room Control Panel</p>
  11    </div>

source/core-api-authorizers-sample/chalice/merge_template.json:
  1  {
  2:     "Description": "AWS Virtual Waiting Room API Sample %%VERSION%%",
  3      "Parameters": {

source/core-api-authorizers-sample/www/waitingroom/index.html:
  8      <title>
  9:         AWS Virtual Waiting Room Entry
  10      </title>

source/openid-waitingroom/chalice/app.py:
  4  This Lambda function provides the endpoint functions
  5: for the OpenID interface of the AWS Virtual Meeting Room
  6  """

source/openid-waitingroom/chalice/merge_template.json:
  1  {
  2:     "Description": "AWS Virtual Waiting Room OpenID Adapter %%VERSION%%",
  3      "Parameters": {

source/openid-waitingroom/www/login.html:
   9      <title>
  10:         AWS Virtual Waiting Room Entry
  11      </title>

source/sample-waiting-room-site/src/views/CheckOut.vue:
  12        You can complete the purchase of your widget now! This component will
  13:       request an authentication token from the AWS Virtual Waiting Room API and
  14        call the site's protected API to finish.

source/shared/aws-virtual-waiting-room-common/setup.py:
  14      author_email="aws-solutions-pdx@amazon.com",
  15:     description="Common Python modules for AWS Virtual Waiting Room",
  16      long_description=long_description,

source/token-authorizer/chalice/merge_template.json:
  1  {
  2:     "Description": "AWS Virtual Waiting Room API Gateway Authorizers %%VERSION%%",
  3      "Parameters": {

**Comment by thyagram-aws** [comment]
Also, the build is failing due to python safety package flagging click - do change the requirements.txt file in the PR?

**Comment by JimTharioAmazon** [comment]
This PR is for public facing documentation and related textual content. We're ok if the build fails since there's no code change here. For the next release, we'll need to schedule the code-related content changes, like templates, externalized strings, workflows, etc.

You should add the deployment/ folder items called out above to #146 so we can track on the 1.1.0 release.

**Review by thyagram-aws — APPROVED** [review]

**Pull request merged**
